version: '3.8'

services:
  api:
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000

  app:
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
 
  # mssql:
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - MSSQL_SA_PASSWORD=Biqwvu987!
  #   ports:
  #     - "1433:1433"